# Generated by Django 4.1 on 2022-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], max_length=20, null=True),
        ),
    ]
