# Generated by Django 4.1 on 2022-08-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
